### ISSUE TITLE
/app/extra is not included in flatpak bundle

### ISSUE THREAD

**Issue by fastrizwaan** [snugglej/org.vivaldi.Vivaldi#5]
I created flatpak, when trying to install it throws this error:

`error: Failed to install bundle org.vivaldi.Vivaldi: Extra data missing in detached metadata`

could you please use `/app/vivaldi` instead of `/app/extra/vivaldi` in the scripts, so that we can bundle flatpak. Thanks.

extra-data is not included in flatpak bundle https://github.com/flatpak/flatpak/issues/1334

**Comment by snugglej** [comment]
Thanks for all your help, I updated the script to look at the new location that vivaldi is moved to and it seems to work on my build 

@fastrizwaan If you want and have time try to pull the latest commit and see if it builds for you.

**Comment by fastrizwaan** [comment]
You're welcome.

**Comment by fastrizwaan** [comment]
Your version fails.
```
flatpak run org.vivaldi.Vivaldi 
[2 zypak-helper] exec failed for /app/extra/vivaldi/vivaldi-bin: No such file or directory (errno 2)
```

**Comment by snugglej** [comment]
Atom failed to push my last change, I just double checked and now the zypak-helper string is updated to point to the right location in this repository.

**Comment by fastrizwaan** [comment]
no, no my my bad, I did not update the vivaldi.sh

**Comment by fastrizwaan** [comment]
https://github.com/snugglej/org.vivaldi.Vivaldi/pull/8 this works now!

**Comment by fastrizwaan** [comment]
Video playback, You can test 
DRM (widewine) https://bitmovin.com/demos/drm
h264 http://demo.nimius.net/video_test/

**Comment by snugglej** [comment]
Accepted #8 and so this should be resolved now. Going to close this out as resolved.
