### ISSUE TITLE
Should be able to create script to pull latest download available for Vivaldi

### ISSUE THREAD

**Issue by snugglej** [snugglej/org.vivaldi.Vivaldi#9]
I think this package would be a lot better if it could build the latest version of vivaldi without having to manual hardcode the packages in each time. 

Also it would be nice to pull the recommended shared objects for ffmpeg and widevine now that we know how to set them properly inside the sandbox environment.

**Comment by snugglej** [comment]
Something like this in a script would be nice,

```
WEBSITE=$(curl -s -N 'https://vivaldi.com/download/' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.214 Safari/537.36 Vivaldi/3.8.2259.42' | grep -oP -e https://downloads.vivaldi.com/[\_A-Za-z0-9\.\/-]*amd64\.deb | uniq )

curl -O $WEBSITE
```

**Comment by develroo** [comment]
You would also need to replace the sha256sum as well that is used to pin the package to a particular version. So the question is how do you automate collecting that sha256sum and verifying it is correct ?

**Comment by vchernin** [comment]
Hi, Flatpak external data checker[Flatpak external data checker](https://github.com/flathub/flatpak-external-data-checker) would make this very easy if this was on Flathub. But it’s possible to use FEDC elsewhere too.

**Comment by snugglej** [comment]
Just going to delete this and look at using the build from: https://github.com/thorhop/com.vivaldi.Vivaldi
